# Generated by Django 3.2.6 on 2021-08-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1. Banners'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': '5. Events'},
        ),
        migrations.AlterModelOptions(
            name='eventattribute',
            options={'verbose_name_plural': '6. ProductAttributes'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '3. Locations'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name_plural': '4. Types'},
        ),
    ]
