# Generated by Django 3.2.6 on 2021-08-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210813_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='eventattribute',
            name='image',
            field=models.ImageField(null=True, upload_to='event_imgs/'),
        ),
    ]
