# Generated by Django 3.2.6 on 2021-08-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_type',
        ),
    ]
