# Generated by Django 3.2.6 on 2021-08-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210825_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='detail',
            new_name='bio',
        ),
    ]
