# Generated by Django 3.2.6 on 2021-08-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_detail_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattribute',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs/'),
        ),
    ]
