# Generated by Django 3.2.6 on 2021-09-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_event_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='otp',
        ),
    ]
