# Generated by Django 3.2.6 on 2021-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattribute',
            name='venue',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
