# Generated by Django 3.2.6 on 2021-10-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_event_clearance_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattribute',
            name='ticket_type',
        ),
    ]
