# Generated by Django 3.2.6 on 2021-10-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_eventattribute_ticket_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Clearance_Form',
            new_name='Police_Clearance_Form',
        ),
    ]
